[project]
name = "uv-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
uv-project = "uv_project:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
